# Generated by Django 6.0.1 on 2026-01-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGPM', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='asesor',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='rol',
            field=models.CharField(choices=[('ASESOR', 'ASESOR'), ('SUPERVISOR', 'SUPERVISOR')], default='ASESOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudmigratoria',
            name='estado_actual',
            field=models.CharField(choices=[('Creada', 'Creada'), ('En revision', 'En revision'), ('Documentos pendientes', 'Documentos pendientes'), ('Enviada', 'Enviada'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cerrada', 'Cerrada'), ('Archivada', 'Archivada')], default='Creada', max_length=30),
        ),
    ]
